namespace CreatorLib
{
    [default_interface]
    runtimeclass IccWriter
    {
        IccWriter();
        Windows.Foundation.IAsyncAction CommitToFileAsync(Windows.Storage.StorageFile file);

        // Header descriptive tags
        String ProfileDescription;
        String ProfileCopyright;

        // Basic profile colorimetry
        Windows.Foundation.Numerics.Vector3 WhitePoint;
        Windows.Foundation.Numerics.Vector3 RedPrimary;
        Windows.Foundation.Numerics.Vector3 GreenPrimary;
        Windows.Foundation.Numerics.Vector3 BluePrimary;
        Single FullFrameLuminance;

        // MHC2 colorimetry
        Single MinLuminance;
        Single PeakLuminance;

        // CSC matrix (note that this is actually a 3x3 matrix, but we use a 4x4 matrix to use built-in matrix multiplication)
        Windows.Foundation.Numerics.Matrix4x4 CscMatrix;

        // MHC2 Re-Gamma LUTS
        Windows.Foundation.Numerics.Vector3[] ReGammaLuts;
    }

    struct ColorMeasure
    {
        Windows.Foundation.Numerics.Vector3 scRGB; // These should be output values that a UI is outputting in an FP16 scRGB space to an HDR panel
		Windows.Foundation.Numerics.Vector3 XYZ;   // These should be the measured values of the output corresponding to the above scRGB values
	};

    [default_interface]
    runtimeclass ColorCalibrationGenerator
    {
        static Windows.Foundation.Numerics.Matrix4x4 ComputeMatrix(ColorMeasure[] measurements);
    }
}
